package autoload

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/van-sprundel/vif/internal/pkg"
)

func TestGenerateCreatesAllFiles(t *testing.T) {
	vendorDir := t.TempDir()

	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Autoload: pkg.Autoload{
				PSR4: map[string][]string{
					`Acme\Foo\`: {"src/"},
				},
			},
		},
	}

	if err := Generate(vendorDir, packages, "testhash123"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	expectedFiles := []string{
		"autoload.php",
		"composer/autoload_real.php",
		"composer/autoload_static.php",
		"composer/autoload_psr4.php",
		"composer/autoload_namespaces.php",
		"composer/autoload_classmap.php",
		"composer/autoload_files.php",
		"composer/ClassLoader.php",
	}

	for _, f := range expectedFiles {
		path := filepath.Join(vendorDir, f)
		if _, err := os.Stat(path); err != nil {
			t.Errorf("missing %s: %v", f, err)
		}
	}
}

func TestGenerateAutoloadPHP(t *testing.T) {
	vendorDir := t.TempDir()

	if err := Generate(vendorDir, nil, "abc123"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "autoload.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "ComposerAutoloaderInitabc123::getLoader()") {
		t.Error("autoload.php should reference ComposerAutoloaderInitabc123")
	}
	if !strings.Contains(content, "@generated by vif") {
		t.Error("autoload.php should contain vif marker")
	}
}

func TestGeneratePSR4(t *testing.T) {
	vendorDir := t.TempDir()

	packages := []pkg.Package{
		{
			Name: "symfony/yaml",
			Autoload: pkg.Autoload{
				PSR4: map[string][]string{
					`Symfony\Component\Yaml\`: {""},
				},
			},
		},
		{
			Name: "acme/lib",
			Autoload: pkg.Autoload{
				PSR4: map[string][]string{
					`Acme\Lib\`: {"src/"},
				},
			},
		},
	}

	if err := Generate(vendorDir, packages, "h1"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// Check autoload_psr4.php
	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_psr4.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, `'Acme\\Lib\\'`) {
		t.Errorf("autoload_psr4.php should contain Acme\\Lib\\ namespace, got:\n%s", content)
	}
	if !strings.Contains(content, `'Symfony\\Component\\Yaml\\'`) {
		t.Errorf("autoload_psr4.php should contain Symfony\\Component\\Yaml\\ namespace")
	}

	// Check autoload_static.php has prefixLengthsPsr4
	staticData, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_static.php"))
	if err != nil {
		t.Fatalf("read static: %v", err)
	}
	static := string(staticData)

	if !strings.Contains(static, "$prefixLengthsPsr4") {
		t.Error("autoload_static.php should contain $prefixLengthsPsr4")
	}
	if !strings.Contains(static, "$prefixDirsPsr4") {
		t.Error("autoload_static.php should contain $prefixDirsPsr4")
	}
}

func TestGeneratePSR0(t *testing.T) {
	vendorDir := t.TempDir()

	packages := []pkg.Package{
		{
			Name: "pear/archive_tar",
			Autoload: pkg.Autoload{
				PSR0: map[string][]string{
					"Archive_Tar": {""},
				},
			},
		},
	}

	if err := Generate(vendorDir, packages, "h2"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_namespaces.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if !strings.Contains(string(data), "'Archive_Tar'") {
		t.Errorf("autoload_namespaces.php should contain Archive_Tar")
	}

	staticData, _ := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_static.php"))
	if !strings.Contains(string(staticData), "$prefixesPsr0") {
		t.Error("autoload_static.php should contain $prefixesPsr0")
	}
}

func TestGenerateFiles(t *testing.T) {
	vendorDir := t.TempDir()

	packages := []pkg.Package{
		{
			Name: "symfony/polyfill",
			Autoload: pkg.Autoload{
				Files: []string{"bootstrap.php"},
			},
		},
	}

	if err := Generate(vendorDir, packages, "h3"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// autoload_files.php should have the md5 key.
	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_files.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	expectedKey := fileHash("symfony/polyfill", "bootstrap.php")
	if !strings.Contains(content, expectedKey) {
		t.Errorf("autoload_files.php should contain key %s, got:\n%s", expectedKey, content)
	}

	// autoload_real.php should contain the files require block.
	realData, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_real.php"))
	if err != nil {
		t.Fatalf("read real: %v", err)
	}
	if !strings.Contains(string(realData), "$filesToLoad") {
		t.Error("autoload_real.php should contain files loading block when files exist")
	}
}

func TestGenerateNoFiles(t *testing.T) {
	vendorDir := t.TempDir()

	packages := []pkg.Package{
		{
			Name: "acme/lib",
			Autoload: pkg.Autoload{
				PSR4: map[string][]string{`Acme\`: {"src/"}},
			},
		},
	}

	if err := Generate(vendorDir, packages, "h4"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	realData, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_real.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if strings.Contains(string(realData), "$filesToLoad") {
		t.Error("autoload_real.php should NOT contain files loading block when no files")
	}
}

func TestGenerateClassmap(t *testing.T) {
	vendorDir := t.TempDir()

	// Create a fake package with PHP files to scan.
	pkgDir := filepath.Join(vendorDir, "acme/mapper", "lib")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "Thing.php"), []byte(`<?php
namespace Acme\Mapper;

class Thing {}
`), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	packages := []pkg.Package{
		{
			Name: "acme/mapper",
			Autoload: pkg.Autoload{
				Classmap: []string{"lib"},
			},
		},
	}

	if err := Generate(vendorDir, packages, "h5"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_classmap.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, `'Acme\\Mapper\\Thing'`) {
		t.Errorf("autoload_classmap.php should contain Acme\\Mapper\\Thing, got:\n%s", content)
	}
}

func TestGeneratePSR4NotInClassmap(t *testing.T) {
	vendorDir := t.TempDir()

	// Create a fake package with only PSR-4 autoload (no explicit classmap).
	// PSR-4 classes should NOT appear in classmap in non-optimized mode —
	// they are resolved at runtime by the ClassLoader.
	pkgSrcDir := filepath.Join(vendorDir, "acme/psr4only", "src")
	if err := os.MkdirAll(pkgSrcDir, 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(filepath.Join(pkgSrcDir, "Widget.php"), []byte(`<?php
namespace Acme\Psr4Only;

class Widget {}
`), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	packages := []pkg.Package{
		{
			Name: "acme/psr4only",
			Autoload: pkg.Autoload{
				PSR4: map[string][]string{
					`Acme\Psr4Only\`: {"src"},
				},
			},
		},
	}

	if err := Generate(vendorDir, packages, "h7"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_classmap.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if strings.Contains(content, `'Acme\\Psr4Only\\Widget'`) {
		t.Errorf("autoload_classmap.php should NOT contain PSR-4 classes in non-optimized mode, got:\n%s", content)
	}
}

func TestGenerateClassLoaderEmbedded(t *testing.T) {
	vendorDir := t.TempDir()

	if err := Generate(vendorDir, nil, "h6"); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "ClassLoader.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	if !strings.Contains(string(data), "class ClassLoader") {
		t.Error("ClassLoader.php should contain the ClassLoader class")
	}
	if !strings.Contains(string(data), "namespace Composer\\Autoload") {
		t.Error("ClassLoader.php should be in Composer\\Autoload namespace")
	}
}

func TestFileHash(t *testing.T) {
	// Deterministic: same input always gives same output.
	h1 := fileHash("acme/lib", "src/helpers.php")
	h2 := fileHash("acme/lib", "src/helpers.php")
	if h1 != h2 {
		t.Errorf("fileHash not deterministic: %q != %q", h1, h2)
	}

	// Different inputs give different hashes.
	h3 := fileHash("acme/lib", "src/other.php")
	if h1 == h3 {
		t.Error("different inputs should give different hashes")
	}

	// Length should be 32 (md5 hex).
	if len(h1) != 32 {
		t.Errorf("fileHash length = %d, want 32", len(h1))
	}
}

func BenchmarkGenerate(b *testing.B) {
	// Build 100 packages with PSR-4 + files.
	packages := make([]pkg.Package, 100)
	for i := range packages {
		packages[i] = pkg.Package{
			Name: fmt.Sprintf("vendor/pkg%d", i),
			Autoload: pkg.Autoload{
				PSR4: map[string][]string{
					fmt.Sprintf(`Vendor\Pkg%d\`, i): {"src/"},
				},
				Files: []string{"helpers.php"},
			},
		}
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		vendorDir := filepath.Join(b.TempDir(), "vendor")
		if err := Generate(vendorDir, packages, "benchhash"); err != nil {
			b.Fatalf("Generate: %v", err)
		}
	}
}
