package autoload

import (
	"fmt"
	"sort"
	"strings"

	"github.com/van-sprundel/vif/internal/pkg"
	"github.com/van-sprundel/vif/internal/version"
)

type PlatformCheckConfig int

const (
	PlatformCheckFull PlatformCheckConfig = iota
	PlatformCheckPHPOnly
	PlatformCheckDisabled
)

func generatePlatformCheck(packages []pkg.Package, mode PlatformCheckConfig) string {
	if mode == PlatformCheckDisabled {
		return ""
	}

	reqs := collectPlatformReqs(packages)
	if reqs.phpBound == nil && !reqs.needs64Bit && len(reqs.extensions) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("<?php\n\n")
	b.WriteString("// platform_check.php @generated by Composer\n\n")
	b.WriteString("$issues = array();\n\n")

	if reqs.phpBound != nil {
		phpID := reqs.phpBound.major*10000 + reqs.phpBound.minor*100 + reqs.phpBound.patch
		fmt.Fprintf(&b, "if (!(PHP_VERSION_ID %s %d)) {\n", reqs.phpBound.op, phpID)
		fmt.Fprintf(&b, "    $issues[] = 'Your Composer dependencies require a PHP version \">= %d.%d.%d\". You are running ' . PHP_VERSION . '.';\n", reqs.phpBound.major, reqs.phpBound.minor, reqs.phpBound.patch)
		b.WriteString("}\n\n")
	}

	if reqs.needs64Bit {
		b.WriteString("if (PHP_INT_SIZE !== 8) {\n")
		b.WriteString("    $issues[] = 'Your Composer dependencies require a 64-bit build of PHP.';\n")
		b.WriteString("}\n\n")
	}

	if mode != PlatformCheckPHPOnly && len(reqs.extensions) > 0 {
		b.WriteString("$missingExtensions = array();\n")
		for _, ext := range reqs.extensions {
			extCheck := fmt.Sprintf("extension_loaded('%s')", ext)
			extName := ext
			if ext == "zend-opcache" {
				extCheck = "extension_loaded('zend opcache')"
				extName = "zend-opcache"
			} else if ext == "pcntl" || ext == "readline" {
				fmt.Fprintf(&b, "PHP_SAPI !== 'cli' || %s || $missingExtensions[] = '%s';\n", extCheck, extName)
				continue
			}
			fmt.Fprintf(&b, "%s || $missingExtensions[] = '%s';\n", extCheck, extName)
		}
		b.WriteString("if ($missingExtensions) {\n")
		b.WriteString("    $issues[] = 'Your Composer dependencies require the following PHP extensions to be installed: ' . implode(', ', $missingExtensions) . '.';\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("if ($issues) {\n")
	b.WriteString("    if (!headers_sent()) {\n")
	b.WriteString("        header('HTTP/1.1 500 Internal Server Error');\n")
	b.WriteString("    }\n")
	b.WriteString("    if (!ini_get('display_errors')) {\n")
	b.WriteString("        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {\n")
	b.WriteString("            fwrite(STDERR, 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . implode(PHP_EOL, $issues) . PHP_EOL.PHP_EOL);\n")
	b.WriteString("        } elseif (!headers_sent()) {\n")
	b.WriteString("            echo 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . str_replace('You are running '.PHP_VERSION.'.', '', implode(PHP_EOL, $issues)) . PHP_EOL.PHP_EOL;\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("    throw new \\RuntimeException(\n")
	b.WriteString("        'Composer detected issues in your platform: ' . implode(' ', $issues)\n")
	b.WriteString("    );\n")
	b.WriteString("}\n")

	return b.String()
}

type phpVersionBound struct {
	major int
	minor int
	patch int
	op    string
}

type platformReqs struct {
	phpBound   *phpVersionBound
	needs64Bit bool
	extensions []string
}

func collectPlatformReqs(packages []pkg.Package) platformReqs {
	var reqs platformReqs
	extSet := make(map[string]bool)

	providedExts := make(map[string]bool)
	for _, p := range packages {
		for name := range p.Provide {
			if strings.HasPrefix(name, "ext-") {
				providedExts[name] = true
			}
		}
		for name := range p.Replace {
			if strings.HasPrefix(name, "ext-") {
				providedExts[name] = true
			}
		}
	}

	var allPHPBounds []phpVersionBound

	for _, p := range packages {
		if p.Require == nil {
			continue
		}
		for name, constraint := range p.Require {
			switch {
			case name == "php":
				c, err := version.ParseConstraint(constraint)
				if err != nil {
					continue
				}
				v, op, ok := c.LowerBound()
				if !ok {
					continue
				}
				allPHPBounds = append(allPHPBounds, phpVersionBound{
					major: v.Major,
					minor: v.Minor,
					patch: v.Patch,
					op:    op,
				})
			case name == "php-64bit":
				reqs.needs64Bit = true
			case strings.HasPrefix(name, "ext-"):
				if providedExts[name] {
					continue
				}
				extName := strings.TrimPrefix(name, "ext-")
				if !extSet[extName] {
					extSet[extName] = true
					reqs.extensions = append(reqs.extensions, extName)
				}
			}
		}
	}

	if len(allPHPBounds) > 0 {
		best := allPHPBounds[0]
		bestID := best.major*10000 + best.minor*100 + best.patch
		for _, b := range allPHPBounds[1:] {
			bID := b.major*10000 + b.minor*100 + b.patch
			if bID > bestID || (bID == bestID && b.op == ">=" && best.op == ">") {
				best = b
				bestID = bID
			}
		}
		reqs.phpBound = &best
	}

	sort.Strings(reqs.extensions)

	return reqs
}
