package autoload

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/van-sprundel/vif/internal/pkg"
	"github.com/van-sprundel/vif/internal/testhelper"
)

func TestPlatformCheckDisabled(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{"php": ">=8.1.0"},
		},
	}

	if err := Generate(vendorDir, packages, "h1", false, nil, true, PlatformCheckDisabled); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if _, err := os.Stat(filepath.Join(vendorDir, "composer", "platform_check.php")); !os.IsNotExist(err) {
		t.Error("platform_check.php should not be generated when disabled")
	}

	realData, _ := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_real.php"))
	if strings.Contains(string(realData), "platform_check.php") {
		t.Error("autoload_real.php should not reference platform_check.php when disabled")
	}
}

func TestPlatformCheckPHPVersion(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{"php": "^8.2"},
		},
	}

	if err := Generate(vendorDir, packages, "h2", false, nil, true, PlatformCheckFull); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "platform_check.php"))
	if err != nil {
		t.Fatalf("read platform_check.php: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "PHP_VERSION_ID >= 80200") {
		t.Errorf("platform_check.php should check PHP >= 8.2.0, got:\n%s", content)
	}
	if !strings.Contains(content, "@generated by Composer") {
		t.Error("platform_check.php should contain generated marker")
	}

	realData, _ := os.ReadFile(filepath.Join(vendorDir, "composer", "autoload_real.php"))
	if !strings.Contains(string(realData), "require __DIR__ . '/platform_check.php'") {
		t.Error("autoload_real.php should require platform_check.php")
	}
}

func TestPlatformCheckExtensions(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{
				"ext-curl":     "*",
				"ext-mbstring": "*",
			},
		},
	}

	if err := Generate(vendorDir, packages, "h3", false, nil, true, PlatformCheckFull); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "platform_check.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "extension_loaded('curl')") {
		t.Errorf("should check ext-curl, got:\n%s", content)
	}
	if !strings.Contains(content, "extension_loaded('mbstring')") {
		t.Errorf("should check ext-mbstring, got:\n%s", content)
	}
}

func TestPlatformCheckPHPOnly(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{
				"php":      ">=8.1",
				"ext-curl": "*",
			},
		},
	}

	if err := Generate(vendorDir, packages, "h4", false, nil, true, PlatformCheckPHPOnly); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "platform_check.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "PHP_VERSION_ID") {
		t.Errorf("should check PHP version, got:\n%s", content)
	}
	if strings.Contains(content, "extension_loaded") {
		t.Errorf("should NOT check extensions in php-only mode, got:\n%s", content)
	}
}

func TestPlatformCheckNoPlatformReqs(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
		},
	}

	if err := Generate(vendorDir, packages, "h5", false, nil, true, PlatformCheckFull); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if _, err := os.Stat(filepath.Join(vendorDir, "composer", "platform_check.php")); !os.IsNotExist(err) {
		t.Error("platform_check.php should not be generated when no platform reqs")
	}
}

func TestPlatformCheck64Bit(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{
				"php-64bit": "*",
			},
		},
	}

	if err := Generate(vendorDir, packages, "h6", false, nil, true, PlatformCheckFull); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "platform_check.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "PHP_INT_SIZE !== 8") {
		t.Errorf("should check 64-bit, got:\n%s", content)
	}
}

func TestPlatformCheckExtSkippedByProvide(t *testing.T) {
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{
				"ext-curl": "*",
			},
		},
		{
			Name:    "acme/polyfill-curl",
			Version: "1.0.0",
			Provide: map[string]string{
				"ext-curl": "*",
			},
		},
	}

	reqs := collectPlatformReqs(packages)
	for _, ext := range reqs.extensions {
		if ext == "curl" {
			t.Error("ext-curl should be skipped when provided by another package")
		}
	}
}

func TestPlatformCheckCLISpecialExtensions(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{
				"ext-pcntl":    "*",
				"ext-readline": "*",
			},
		},
	}

	if err := Generate(vendorDir, packages, "h7", false, nil, true, PlatformCheckFull); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "platform_check.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "PHP_SAPI !== 'cli' || extension_loaded('pcntl')") {
		t.Errorf("pcntl should use CLI guard, got:\n%s", content)
	}
	if !strings.Contains(content, "PHP_SAPI !== 'cli' || extension_loaded('readline')") {
		t.Errorf("readline should use CLI guard, got:\n%s", content)
	}
}

func TestPlatformCheckHighestPHPBound(t *testing.T) {
	vendorDir := testhelper.TempDir(t, "vendor")
	packages := []pkg.Package{
		{
			Name:    "acme/foo",
			Version: "1.0.0",
			Require: map[string]string{"php": ">=7.4"},
		},
		{
			Name:    "acme/bar",
			Version: "2.0.0",
			Require: map[string]string{"php": "^8.1"},
		},
		{
			Name:    "acme/baz",
			Version: "1.5.0",
			Require: map[string]string{"php": ">=8.0"},
		},
	}

	if err := Generate(vendorDir, packages, "h8", false, nil, true, PlatformCheckFull); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(vendorDir, "composer", "platform_check.php"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "PHP_VERSION_ID >= 80100") {
		t.Errorf("should use highest PHP bound 8.1.0, got:\n%s", content)
	}
}
