package autoload

import _ "embed"

//go:embed embed/ClassLoader.php
var classLoaderPHP string

// PHP templates for generated autoloader files.
// <HASH> is replaced with the autoload hash at generation time.

const autoloadPHP = `<?php

// autoload.php @generated by vif

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit<HASH>::getLoader();
`

const autoloadRealPHP = `<?php

// autoload_real.php @generated by vif

class ComposerAutoloaderInit<HASH>
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit<HASH>', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit<HASH>', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit<HASH>::getInitializer($loader));

        $loader->register(true);

        <FILES_REQUIRE>

        return $loader;
    }
}
`

// filesRequireBlock is inserted into autoload_real.php when there are files to autoload.
const filesRequireBlock = `$filesToLoad = \Composer\Autoload\ComposerStaticInit<HASH>::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }`

const autoloadStaticPHP = `<?php

// autoload_static.php @generated by vif

namespace Composer\Autoload;

class ComposerStaticInit<HASH>
{
<STATIC_FILES>
<STATIC_PREFIX_LENGTHS_PSR4>
<STATIC_PREFIX_DIRS_PSR4>
<STATIC_PREFIXES_PSR0>
<STATIC_CLASSMAP>
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
<INITIALIZER_BODY>
        }, null, ClassLoader::class);
    }
}
`

const autoloadPsr4PHP = `<?php

// autoload_psr4.php @generated by vif

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
<PSR4_ENTRIES>
);
`

const autoloadNamespacesPHP = `<?php

// autoload_namespaces.php @generated by vif

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
<PSR0_ENTRIES>
);
`

const autoloadClassmapPHP = `<?php

// autoload_classmap.php @generated by vif

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
<CLASSMAP_ENTRIES>
);
`

const autoloadFilesPHP = `<?php

// autoload_files.php @generated by vif

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
<FILES_ENTRIES>
);
`
